env:
  browser: true
  es2021: true
  jest: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules: {
  "react/react-in-jsx-scope": "off",
  "no-console": [1, { "allow": ["error"] }],
  "no-debugger": 1,
  "class-methods-use-this": 0,
  "max-len": [1,200,2],
  "no-trailing-spaces": [0],
  "quotes": [2, "single"],
  'react/jsx-max-props-per-line': [
      2,
      { maximum: 1, when: 'multiline' },
    ],
}